# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1901ce4ce87f2ca77e87a5ec986a771d410386de0bfa78725c40e06f2df92e7759f8b8673e855b95a5c533e22f230008f62cf0b23038408ec3ee55dbce2991b

test:
  secret_key_base: 0a8d5e224fb682312f79b3f0aaf1e017d2e3043bbf0fa2e6099afcf3258521702249896c1975f5083782754e08ddc2673c6ab9bb8cf08ae35e0326bfdc6a1b34

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
